### PR TITLE
More example scenes

### PR DESCRIPTION
**Pull request by tlian7**
@benjamin-heasly 

These are the updated example scenes from our end.

### CODE REVIEW

**Comment by benjamin-heasly** [comment]
Hi @tlian7,

Cool.  Thanks.  I'll start reviewing this.

**Comment by benjamin-heasly** [comment]
Hi @tlian7,

Looking good.

I made a few minor changes.  Mainly, so that I could run each example without having to `cd()` to each example folder.  This is just a style choice -- I think it's good when code doesn't depend on the value of `pwd()`.

I also moved the examples that depend on isetbio into a subfolder folder called `ExampleScenes/IsetbioExamples`.   I added a `README.md` to this folder to point out the dependency on isetbio, and make suggestions for how to get isetbio.

So, cool.

Before we merge this, could you run the examples again and verify that they still look good on your end?

**Comment by tlian7** [comment]
Hi @benjamin-heasly,

Thanks for the adjustments. I'll re-check these scenes and let you know how it goes. I'm currently rendering a large set of images that I'm still waiting on to finish, so I might not be able to check until sometime mid-tomorrow.

**Comment by benjamin-heasly** [comment]
Hi @tlian7 --

I edited the Crytek Sponza example to show how you can use an anonymous function to pass an extra parameter to a remodeler function.  In this case, the parameter is called `cameraInfo`, but you could change that to whatever you want. 

The `cameraInfo` is defined once at the top of the top-level script, passed to the remodeler, and could also be used below for iset stuff.

Does that do what you need?

**Comment by tlian7** [comment]
Yes, that cameraInfo adjustment seems like a good and simple solution to this. I'll play around with it with some of the other scripts to see if it solves all our problems and let you know how it goes.

Thanks again!

**Pull request merged**
